name: Confirmar Build Real ISO

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Instalar 7zip e aria2
      shell: cmd
      run: |
        choco install 7zip -y
        choco install aria2 -y

    - name: Baixar ISO (3 partes)
      shell: cmd
      run: |
        aria2c -x16 -s16 -k1M --file-allocation=none -o base.7z.001 https://github.com/Loopz976/ltsc-auto-builder/releases/download/w10-ltsc-1288/w10-ltsc-1288.7z.001
        aria2c -x16 -s16 -k1M --file-allocation=none -o base.7z.002 https://github.com/Loopz976/ltsc-auto-builder/releases/download/w10-ltsc-1288/w10-ltsc-1288.7z.002
        aria2c -x16 -s16 -k1M --file-allocation=none -o base.7z.003 https://github.com/Loopz976/ltsc-auto-builder/releases/download/w10-ltsc-1288/w10-ltsc-1288.7z.003

    - name: Extrair pacote 7z
      shell: cmd
      run: |
        7z x base.7z.001 -y

    - name: Selecionar ISO correta
      shell: cmd
      run: |
        set ISO_FOUND=0

        for /r %%i in (pt-br_windows_10_enterprise_ltsc_2021_x64_dvd_f318268e.iso) do (
          if exist "%%i" (
            echo ISO encontrada: %%i
            copy "%%i" win10.iso
            set ISO_FOUND=1
            goto :done
          )
        )

        :done

        if %ISO_FOUND%==0 (
          echo ERRO: ISO nao encontrada
          dir /s *.iso
          exit /b 1
        )

    - name: Extrair ISO
      shell: cmd
      run: |
        mkdir ISO
        7z x win10.iso -oISO -y

    - name: Mostrar info COMPLETA da build
      shell: cmd
      run: |
        echo ==============================
        echo BUILD REAL DO WINDOWS
        echo ==============================

        if exist ISO\sources\install.wim (
          dism /Get-ImageInfo /ImageFile:ISO\sources\install.wim /Index:1
        ) else (
          dism /Get-ImageInfo /ImageFile:ISO\sources\install.esd /Index:1
        )

        echo ==============================
        echo FIM DA VERIFICACAO
        echo ==============================
